# Generated by Django 4.1.3 on 2022-11-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=''),
        ),
    ]
